export const projects = [
  {
    img: "/assets/imgs/message_board_preview.png",
    name: "Message Board",
    description: "pr_message_board_desc",
    tech: "React, NodeJS, JWT, Express, Sequelize, API Rest",
    repo: "https://github.com/nleo-m/message-board",
    preview: false,
  },
  {
    img: "/assets/imgs/weather_app_preview.png",
    name: "Weather APP",
    description: "pr_weather_app_desc",
    tech: "Vue, API",
    repo: "https://github.com/nleo-m/weather-app",
    preview: "https://nleo-m.github.io/weather-app/",
  },
  {
    img: "/assets/imgs/virtual_assist_preview.png",
    name: "My Virtual Assistant",
    description: "pr_virtual_assistant_desc",
    tech: "Python",
    repo: "https://github.com/nleo-m/my-virtual-assistant",
    preview: false,
  },
  {
    img: "/assets/imgs/focus_point_preview.png",
    name: "Focus point",
    description: "pr_focus_point_desc",
    tech: "React native, react",
    repo: "https://github.com/nleo-m/focus-point",
    preview: false,
  },
  {
    img: "/assets/imgs/cool_rainbows_preview.png",
    name: "C00l Rainbows",
    description: "pr_cool_rainbows_desc",
    tech: "Javascript",
    repo: "https://github.com/nleo-m/cool-rainbows",
    preview: "https://nleo-m.github.io/cool-rainbows/",
  },
];
